# Generated by Django 5.1.15 on 2026-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_kk',
            field=models.TextField(blank=True, default='', verbose_name='Ответ (KK)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, default='', verbose_name='Ответ (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kk',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос (KK)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос (RU)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ (EN, default)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Вопрос (EN, default)'),
        ),
    ]
