# Generated by Django 5.1.15 on 2026-05-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notif_user_idx_notificatio_user_id_e78525_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Задача назначена'), ('step_completed', 'Шаг завершён'), ('document_signed', 'Документ подписан'), ('new_comment', 'Новый комментарий'), ('deadline_approaching', 'Срок истекает'), ('document_rejected', 'Документ отклонён'), ('org_invitation', 'Приглашение в организацию')], db_index=True, max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
