# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chatmess_user_id_2ac7ef_idx',
            old_name='ai_chatmsg_user_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chatmess_user_id_3f4eea_idx',
            old_name='ai_chatmsg_user_ws_idx',
        ),
        # Индекс documentembedding создан в 0001 сырым SQL и НЕ зарегистрирован
        # в состоянии Django, поэтому обычный RenameIndex по имени падает с
        # "No index named ai_docembed_doc_chunk_idx". Переименовываем только в БД;
        # в состоянии Django индекс будет добавлен позже (миграция 0004).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS ai_docembed_doc_chunk_idx "
                        "RENAME TO ai_document_documen_a703d6_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS ai_document_documen_a703d6_idx "
                                "RENAME TO ai_docembed_doc_chunk_idx;",
                ),
            ],
            state_operations=[],
        ),
    ]
