# Generated by Django 5.1.15 on 2026-05-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_ai_chatmsg_user_doc_idx_ai_chatmess_user_id_2ac7ef_idx_and_more'),
        ('documents', '0007_blockchainblock'),
    ]

    operations = [
        # Индекс ai_document_documen_a703d6_idx уже создан физически в 0003
        # (RenameIndex из ai_docembed_doc_chunk_idx). Поэтому в БД ничего не
        # создаём — иначе CREATE INDEX падает с "relation already exists".
        # Регистрируем индекс только в состоянии Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='documentembedding',
                    index=models.Index(fields=['document', 'chunk_index'], name='ai_document_documen_a703d6_idx'),
                ),
            ],
        ),
        migrations.AlterModelTable(
            name='documentembedding',
            table=None,
        ),
    ]
