# Generated by Django 5.1.15 on 2026-05-30 09:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_documentembedding_vector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, verbose_name='Векторное представление'),
        ),
    ]
