# Generated by Django 5.1.15 on 2026-05-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        ('workspaces', '0002_add_workspace_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(default='viewer', max_length=20, verbose_name='Роль в кабинете'),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='workspaces.workspace', verbose_name='Кабинет'),
        ),
    ]
