# Generated by Django 5.1.15 on 2026-04-24 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='documentauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлён'), ('archived', 'Архивирован'), ('workflow_started', 'Workflow запущен'), ('signed', 'Подписан'), ('approved', 'Согласован'), ('version_uploaded', 'Версия загружена'), ('comment_added', 'Комментарий добавлен'), ('downloaded', 'Скачан')], db_index=True, max_length=50, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('storage_key', models.TextField(verbose_name='Ключ S3')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document', verbose_name='Документ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'document_attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document'], name='document_at_documen_3cbbfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название подзадачи')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Выполнено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'db_table': 'subtasks',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document'], name='subtasks_documen_728fe5_idx'), models.Index(fields=['assignee'], name='subtasks_assigne_562bec_idx'), models.Index(fields=['status'], name='subtasks_status_ab6b89_idx')],
            },
        ),
    ]
