# Generated by Django 5.1.15 on 2026-05-15 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_content_fields'),
        ('tasks', '0005_rename_tasks_reque_request_idx_tasks_request_d1e7fd_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(default=0, verbose_name='Порядковый номер шага')),
                ('document_hash', models.CharField(help_text='Хеш файла документа в момент завершения задачи', max_length=64, verbose_name='SHA-256 документа')),
                ('previous_hash', models.CharField(max_length=64, verbose_name='Хеш предыдущего блока')),
                ('block_hash', models.CharField(db_index=True, help_text='SHA-256(previous_hash + document_hash + task_id + timestamp)', max_length=64, verbose_name='Хеш блока')),
                ('timestamp', models.DateTimeField(verbose_name='Время создания блока')),
                ('tampered', models.BooleanField(db_index=True, default=False, help_text='True если хеш документа не совпадает с предыдущим блоком', verbose_name='Документ изменён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_blocks', to='documents.document', verbose_name='Документ')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_block', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Blockchain блок',
                'verbose_name_plural': 'Blockchain блоки',
                'db_table': 'document_blockchain',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='document_bl_documen_f02dc0_idx')],
            },
        ),
    ]
