# Generated by Django 5.1.15 on 2026-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_blockchainblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainblock',
            name='task_id_str',
            field=models.CharField(blank=True, default='', help_text='Строковый UUID задачи на момент создания блока', max_length=36, verbose_name='Task ID (снимок)'),
        ),
    ]
