# Generated by Django 5.1.15 on 2026-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_task_id_str_to_blockchain_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
