# Generated by Django 5.1.15 on 2026-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные подписи (base64 PNG)'),
        ),
    ]
