# Generated by Django 5.1.15 on 2026-05-14 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_add_workspace_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('signer', 'Подписант'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('declined', 'Отклонена')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённый')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invitations', to='workspaces.workspace', verbose_name='Кабинет')),
            ],
            options={
                'db_table': 'workspace_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
