# Generated by Django 5.1.15 on 2026-05-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_request_type_extended_statuses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_request_d1e7fd_idx',
            old_name='tasks_reque_request_idx',
        ),
    ]
